name: 
    hello world测试

on: 
    push:
    schedule:
        - cron: '*/5 * * * *' 
    workflow_dispatch:

jobs:
    say-hello:
        name: 打印问候语
        runs-on: ubuntu-latest

        steps:
            - name: 打印Say Hello
              run: echo "Hello, World!"

