name: 
    hello world

on: 
    push:
    schedule:
        - cron: '* * * * *' 

jobs:
    say-hello:
        name: 打印问候语
        runs-on: ubuntu-latest

        steps:
            - name: 打印Say Hello
              run: echo "Hello, World!"

