name: 
    hello world

on: 
    push

jobs:
    say-hello:
        name: 打印问候语
        runs-on: ubuntu-latest

        steps:
            - name: 打印Say Hello
              run: echo "Hello, World!"

