name: 矩阵构建

on:
    push:
    workflow_dispatch:

jobs:
    test-matrix:
        name: 测试Node:${{matrix.node}} on ${{matrix.os}}
        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: ['18', '20', '22'] 
            fail-fast: false

        steps:
            - uses: actions/checkout@v4

            - name: 配置nodejs${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
               node-version: ${{ matrix.node }}


            - name: 查看nodejs版本
              run: |
               node --version
               npm --version