name: secrets密钥
on:
  push:

jobs:
    
    miyao:
        runs-on: ubuntu-latest

        steps:
            - run: |
                echo "获取secrets密钥"
                echo "secrets密钥: ${{ secrets.MXBB }}"